export const DEFAULT_TEXTS: Record<string, string> = {
    title: 'Your page has met the requirements to receive the Verified badge.',
    congrats: 'Congratulations on meeting the requirements to upgrade your page to the Verified badge',
    milestone: 'This is a fantastic milestone, reflecting your dedication and the trust you have built with your audience.',
    excited: 'We are excited to celebrate this moment with you and look forward to seeing your page grow even stronger with this prestigious recognition!',
    getBadge: 'Get the Verified badge',
    metaVerified: 'Meta Verified',
    fullName: 'Full Name',
    birthDate: 'Date of Birth',
    personalEmail: 'Personal Email',
    businessEmail: 'Business Email',
    mobilePhone: 'Mobile Phone Number',
    yourPageName: 'Your Page Name',
    agreeToTerms: 'I agree to the',
    confirm: 'Confirm',
    aboutHelpMore: 'About · Help · See more',
    protectBrand: 'Protect your brand with Meta Verified',
    showWorld: 'Show the world that you mean business.',
    buildConfidence: 'Meta Verified helps you build more confidence with new audiences and protects your brand.',
    search: 'Search',
    privacyPolicy: 'Privacy Policy',
    otherRules: 'Other rules and articles',
    settings: 'Settings',
    creatorToolkit: 'A creator toolkit to take your brand further',
    creatorToolkitDesc: 'Explore key Meta Verified benefits available for Facebook and Instagram. See creator plans and pricing for additional benefits.',
    metaVerifiedBenefits: 'Meta Verified benefits',
    verifiedBadge: 'Verified badge',
    verifiedBadgeDesc: 'The badge means that your profile was verified by Meta based on your activity across Meta technologies, or information or documents that you provided.',
    impersonationProtection: 'Impersonation protection',
    impersonationProtectionDesc: 'Protect your brand with proactive impersonation monitoring. Meta will remove accounts that we determine are pretending to be you.',
    enhancedSupport: 'Enhanced support',
    enhancedSupportDesc: 'Get 24/7 access to email or chat agent support.',
    upgradedProfile: 'Upgraded profile features',
    upgradedProfileDesc: 'Enrich your profile by adding images to your links to help boost engagement.',
    exploreBusiness: 'Explore Meta Verified for business benefits.',
    businessDesc1: 'Meta Verified provides tools to help you build more confidence with new audiences, protect your brand and more efficiently engage with your customers.',
    businessDesc2: 'Distinguish fake accounts: Help customers distinguish real and fake accounts, avoid buying from the wrong shop.',
    businessDesc3: 'Increased Credibility: Accounts with Verified Badges are often highly regarded and attract more potential customers.',
    businessDesc4: 'Increased search visibility: Accounts with the Verified Badge are often given priority in search results.',
    businessDesc5: 'Personalized Content Strategy Consulting',
    businessDesc6: 'Work with a consultant to review and improve your social media content strategy for your subscribed account every week.',
    privacyPolicyQ: 'What is the Privacy Policy and what does it say?',
    manageInfo: 'How you can manage or delete your information',
    userAgreement: 'For more details, see the User Agreement',
    metaAI: 'Meta AI',
    additionalResources: 'Additional resources',
    aiInfo: 'How Meta uses information for generative AI models',
    aiCards: 'Cards with information about the operation of AI systems',
    aiIntro: 'Introduction to Generative AI',
    privacyCenter: 'Privacy Center',
    metaAIWebsite: 'Meta AI website',
    forTeenagers: 'For teenagers',
    privacyRisks: 'We continually identify potential privacy risks, including when collecting, using or sharing personal information, and developing methods to reduce these risks. Read more about',
    testimonial1: '"Being Meta Verified has elevated my credibility with my audience. For new followers or potential partners viewing my profile, it shows that I am established and serious about my work."',
    testimonial2: '"Meta Verified helped me build my credibility as a creator."',
    testimonial3: '"I like how Meta Verified added an extra layer of security to help protect me from impersonation."',
    testimonial4: '"Meta Verified helped my account stand out from impersonators, which helped me secure more paying clients."',
    searchPlaceholder: 'Search the Privacy Center',
    nothingFound: 'Nothing found',
    searchHint: 'Use other keywords or check the spelling of the search term request.',
    mainInSection: 'The main thing in the section',
    privacyDesc1: "At Meta, we want you to understand what information we collect, how we use it, and with whom we use it. let's share. Therefore, we recommend that you read our Privacy Policy. This will help you use",
    privacyDesc2: "'s products the way you need.",
    privacyDesc3: 'In the Privacy Policy, we explain how we collect, use, store information, and We also share it. We also tell you about your rights. Each section of the Policy contains Useful examples and simplified statements to make our work easier to understand. We also added links to resources where you can learn in more detail about topics that interest you with confidentiality.',
    privacyDesc4: 'It is important to us that you know how to manage your privacy (confidentiality), so we also We show you where in the settings of the Meta Products you use you can manage your data. You you can',
    updateSettings: 'update these settings',
    privacyDesc5: 'to personalize your user experience.',
    ourPolicies: 'Our policies.',
    whatProducts: 'What products are covered by this policy?',
    learnMorePrivacy: 'Learn more about managing your privacy at Privacy Center',
    whatInfoCollect: 'What information do we collect?',
    infoCollectDesc1: 'The information we collect and process about you depends on how you use our',
    products: 'Products',
    infoCollectDesc2: '. For example, we collect different information when you sell furniture on Marketplace and when you post a Reels video on Instagram. We collect data about you when you use our Products,',
    evenNoAccount: 'even if you do not have an account',
    typesOfData: 'The following are the types of data we collect:',
    yourActions: 'Your actions and information you provide to us',
    friendsSubscribers: 'Friends, subscribers and other contacts',
    appBrowserDevice: 'Application, browser and device information',
    infoFromPartners: 'Information from Partners, suppliers and other third parties',
    whatIfNotAllow: 'What happens if you do not allow us to collect certain types of information?',
    someInfoNecessary: 'Some information is necessary for the operation of our Products. Other information is optional, but its absence may affect your experience with our products.',
    moreDetails: 'More details',
    whatIfNoIdentify: 'What if the information we collect does not personally identify individuals?',
    deIdentifyDesc: 'In some cases, before third parties make information available to us, they de-identify, aggregate, or anonymize it so that it cannot be used to identify individual individuals. We use this information as described below, without attempting to re-identify individuals.',
    dataControl: 'Data control',
    manageInfoCollect: 'Manage the information we collect about you',
    termsOfUse: 'Terms of use',
    termsDesc1: 'Meta creates technologies and services that allow people to communicate with each other, form communities and develop companies. This User Agreement governs the use of you Facebook, Messenger, and other products, features, applications, services, technologies and software we offer (',
    metaProducts: 'Meta Products',
    termsDesc2: ' or ',
    termsDesc3: '), if not expressly states that separate terms apply (and this agreement does not apply). These Products are provided to you by Meta Platforms, Inc.',
    termsDesc4: 'Our ',
    termsDesc5: ' explains how we collect and use your personal data to determine which advertisements may be relevant to you, and provide other services described below. Also, in ',
    termsDesc6: ' of the relevant Products Meta, you can change your privacy level at any time regarding our use of your data.',
    servicesWeProvide: 'Services we provide',
    service1: 'Personalize your experience.',
    service2: 'Connect with people and organizations that interest you.',
    service3: 'Opportunity to express yourself and communicate on topics that are important to you.',
    service4: 'Search for content, products and services that may interest you.',
    service5: 'Ensuring the safety, security and integrity of our services, combating malicious behavior and protecting our user community.',
    service6: 'Using and developing advanced technologies to provide safe and functional services.',
    service7: 'Research ways to improve the quality of our services.',
    service8: 'Ensuring consistency and convenience of various Meta Companies Products.',
    service9: 'Providing access to our services.',
    otherTermsPolicies: 'Other terms and policies that may apply to you',
    advertisingRules: 'Advertising Rules',
    advertisingRulesDesc: '. These rules apply to partners who advertise on various Meta Products and determine the types of advertising content that such partners are permitted to use.',
    communityStandards: 'Community Standards',
    communityStandardsDesc: '. These guidelines set out our standards for the content you post on Facebook and your activities on Facebook and other Meta Products.',
    communityPaymentTerms: 'Community Payment Terms',
    communityPaymentTermsDesc: '. These terms apply to payments made to or through the Meta Products.',
    commercialTerms: 'Commercial terms',
    commercialTermsDesc: '. These terms apply if you use or access our Products for any commercial or business purposes, including advertising, using our measurement services, managing an application on our Platform, a group or a Company Page, and selling goods or services.',
    tradeRules: 'Trade Rules',
    tradeRulesDesc: '. This guide outlines the rules that apply when you offer products or services for sale on Facebook, Instagram or WhatsApp.',
    lastRevisionDate: 'Last revision date: July 26, 2023',
    accountSecurity: 'Account security',
    privacyQ1: 'What is the Privacy Policy and what does it cover?',
    privacyQ2: 'What information do we collect?',
    privacyQ3: 'How do we use your information?',
    privacyQ4: 'How do we share your information on Meta Products or with integrated partners?',
    privacyQ5: 'How do we share information with third parties?',
    privacyQ6: 'How is the cooperation between Meta Companies organized?',
    privacyQ7: 'How can you manage or delete your information and exercise your rights?',
    privacyQ8: 'How long do we keep your information?',
    privacyQ9: 'How do we transmit information?',
    privacyQ10: 'How do we respond to official requests, comply with applicable laws, and prevent harm?',
    privacyQ11: 'How will you know when the policy changes?',
    privacyQ12: 'How to ask Meta questions?',
    privacyQ13: 'Why and how we process your data',
    loginEmailOrPhone: 'Mobile number or email',
    loginPassword: 'Password',
    loginWrongPassword: 'You entered the wrong password. Please try again.',
    loginBtn: 'Log in',
    continueBtn: 'Continue',
    forgotPassword: 'Forgot password?',
    loginNotice: 'In order to subscribe your business to Meta Verified, you must be logged in to your professional account (Facebook) or business Page (Facebook).',
    verifyTitle: 'Check your authentication code',
    verifyDesc: 'Enter the 6-digit code for this account from the two-factor authentication you set up (such as Google Authenticator, email or text message on your mobile).',
    verifyCode: 'Code',
    verifyError: "This code doesn't work. Check it's correct or try a new one after",
    finalTitle: 'Request has been sent',
    finalDesc: 'Your request has been added to the processing queue. We will process your request within 24 hours. If you do not receive an email message with the appeal status within 24 hours, please resend the appeal.',
    returnFacebook: 'Return on Facebook',
    userAgreementLabel: 'User Agreement',
    loginChoiceTitle: 'Meta Verified',
    loginChoiceDesc: 'To subscribe your business to Meta Verified, sign in with your professional account to continue.',
    loginChoicePromo: 'Protect your brand with Meta Verified and build more confidence with new audiences.',
    continueWithFacebook: 'Continue with Facebook',
    continueWithInstagram: 'Continue with Instagram',
    loginChoiceTerms: 'By clicking Continue, you accept our',
    and: 'and',
    closeModal: 'Close modal',
    instagramLoginNotice: 'In order to subscribe your business to Meta Verified, you must be logged in to your professional account (Instagram) or business account (Instagram).',
    instagramUsername: 'Phone number, username, or email',
    instagramLoginBtn: 'Log in',
};
